debug: true

server:
  port: 8080

spring:
  cache:
    type: redis
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:app_db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  redis:
    host: ${REDIS_HOST:192.168.99.101}
    port: ${REDIS_PORT:30302}
#    sentinel:
#      master: mymaster
#      nodes: redis-ha:26379

